project/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, 
              controllers:{sessions: 'users/sessions', 
                           registrations: 'users/registrations', 
                           confirmations: 'users/confirmations', 
                           passwords: 'users/passwords', 
                           unlocks: 'users/unlocks'}

  get 'welcome/index'

  root 'welcome#index'

  get '/about', to: 'welcome#about'

  get '/contact', to: 'welcome#contact'

  get '/scratchpad/:scratchpad_id', to: 'welcome#scratchpad'

  get '/usertest1', to: 'welcome#usertest1'
  
  get '/help', to: 'welcome#help'

  get '/profile', to: 'welcome#profile'
      
  get '/team', to: 'welcome#team'

  get '/usertest2', to: 'useronly#usertest2'
  
  get '/samplemodel', to: 'welcome#sampleget'

  get '/dashboard', to: 'welcome#dashboard'
  
  post '/samplemodel', to: 'welcome#samplepost'
  
  post '/save_scratchpad_data', to: 'welcome#save_scratchpad_data'
  
  post '/create_scratchpad', to: 'welcome#create_scratchpad'

end

project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Project</title>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <header class="navbar navbar-fixed-top navbar-inverse">

      <div class="navbar-inner">

        <div class="container">
            <nav class="navbar">
            		
				

		<div>
		<ul>
  			<li>
   			 <a href ="" class = "button">More</a>
    		<ul>
      		<li><%= link_to "Home", root_path %></li>
      		<li><%= link_to "Tutorial", tutorial_path %></li>
      		<li><%= link_to "About", about_path %></li>
      		<li><%= link_to "Contact", contact_path %></li>
      		<li><%= link_to "Profile", profile_path %></li>
      		<li><%= link_to "Register", register_path %></li>
      		<li><%= link_to "Team", team_path %></li>
      		<li><%= link_to "Register", register_path %></li>
        	<li><%= link_to "Help", help_path %></li>
    
   		    </ul>
  			</li>
  		</ul>
  		<%-# second way of creating a clickable image -%>
		<a href="http://localhost:3000" class="svg">
  		<img src="/assets/Algebreezy_draft.svg" style="width:650px;height:40px;vertical-align:middle">
  		</a>
  		
  		<%-#place holders for login and logout button -%>
  		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    	<a href ="http://localhost:3000/login" class = "button">Login</a>
        <a href ="http://localhost:3000/logout" class = "button" >Logout</a>

	  </div>
            </nav>
        </div>
      </div>
    </header>
    
    <div class="container">

      <% flash.each do |key, value| %>

          <%= content_tag(:div, value, class: "alert alert-#{key}") %>

      <% end %>

      <%= yield %>


    </div>
</html>

project/app/views/layouts/devise_layout.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Project</title>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
      <% flash.each do |key, value| %>

          <%= content_tag(:div, value, class: "alert alert-#{key}") %>

      <% end %>
        <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <body>
            <nav class="navbar">

            <div>
                <div id="dropdown_menu">
                    <a href ="" class = "button" >More</a>
                    <div id="dropdown_submenu">
                        <li><%= link_to "Home", root_path %></li>
                        <li><%= link_to "About", about_path %></li>
                        <li><%= link_to "Contact", contact_path %></li>
                        <li><%= link_to "Help", help_path %></li>
                        <li><%= link_to "Profile", profile_path %></li>                     
                        <li><%= link_to "Register", new_user_registration_path %></li>
                        <li><%= link_to "Team", team_path %></li>
                        <% if user_signed_in? %>
                            <li><%= link_to "Dashboard", dashboard_path %></li>
                        <% end %>
                    </div>
                </div>
                <% if user_signed_in? %>
                    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'button', :id => 'logout_button'  %>
                <% else %>
                    <%= link_to "Login", new_user_session_path, :class => 'button', :id => 'login_button'  %>
                <% end %>
                
                <div id="title-image-container" onclick="location.href='/'">
                        <%= image_tag "Algebreezy_draft_3.svg" , class: 'algebreezy-svg'%>
                </div>

            </div>
    </nav>
    
    <div class="flash_message"></div>
            <div class="body_content">
                <%= yield %>
            </div>
        </body>

    </div>
</html>

project/app/views/layouts/general_layout.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Algebreezy</title>
        <script src='https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>   
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular.min.js"></script>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <nav class="navbar">

            <div>
                <div id="dropdown_menu">
                    <a href ="" class = "button" >More</a>
                    <div id="dropdown_submenu">
                        <li><%= link_to "Home", root_path %></li>
      					<li><%= link_to "About", about_path %></li>
      					<li><%= link_to "Contact", contact_path %></li>
        				<li><%= link_to "Help", help_path %></li>  
      					<li><%= link_to "Profile", profile_path %></li>    					
      					<li><%= link_to "Register", new_user_registration_path %></li>
      					<li><%= link_to "Team", team_path %></li>
      					
                        <% if user_signed_in? %>
                            <li><%= link_to "Dashboard", dashboard_path %></li>
                        <% end %>
                    </div>
                </div>
                <% if user_signed_in? %>
                    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'button', :id => 'logout_button'  %>
                <% else %>
                    <%= link_to "Login", new_user_session_path, :class => 'button', :id => 'login_button'  %>
                <% end %>
                
                <div id="title-image-container" onclick="location.href='/'">
                        <%= image_tag "Algebreezy_draft_3.svg" , class: 'algebreezy-svg'%>
                </div>

            </div>
    </nav>
    <div class="flash_message">
        <% flash.each do |key, value| %>

            <%= content_tag(:div, value, class: "alert alert-#{key}") %>

        <% end %>
        <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
        <% end %>
    </div>
    <div class="body_content">
        <%= yield %>
    </div>
    </body>

    </div>
</html>

project/app/views/layouts/scratchpad_layout.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Algebreezy</title>
        <script src='https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>   
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular.min.js"></script>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'scratchpad_scripts', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <nav class="navbar">

            <div>
                <div id="dropdown_menu">
                    <a href ="" class = "button" >More</a>
                    <div id="dropdown_submenu">
                        <li><%= link_to "Home", root_path %></li>
                        <li><%= link_to "About", about_path %></li>
                        <li><%= link_to "Contact", contact_path %></li>
                        <li><%= link_to "Help", help_path %></li>
                        <li><%= link_to "Profile", profile_path %></li>                     
                        <li><%= link_to "Register", new_user_registration_path %></li>
                        <li><%= link_to "Team", team_path %></li>
                        <% if user_signed_in? %>
                            <li><%= link_to "Dashboard", dashboard_path %></li>
                        <% end %>
                    </div>
                </div>
                <% if user_signed_in? %>
                    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'button', :id => 'logout_button'  %>
                <% else %>
                    <%= link_to "Login", new_user_session_path, :class => 'button', :id => 'login_button'  %>
                <% end %>
                
                <div id="title-image-container" onclick="location.href='/'">
                        <%= image_tag "Algebreezy_draft_3.svg" , class: 'algebreezy-svg'%>
                </div>

            </div>
    </nav>
    <div class="flash_message">
        <% flash.each do |key, value| %>

            <%= content_tag(:div, value, class: "alert alert-#{key}") %>

        <% end %>
        <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
        <% end %>
    </div>
    <div class="scratchpad_content">
        <%= yield %>
    </div>
    </body>

    </div>
</html>